### PR TITLE
Ga tw 32 add new questions

### LINKED ISSUE #32: Add in Performer-related True/False questions
[timebox: 2 hours, complexity points: 2]

As a user, I would like to see a wider variety of questions asked so that game play will be more interesting.

As a developer, I would like to integrate different information from the API to generate a wider variety of questions for the player to answer.

**Developer Dependencies**
- Get Credits API data object
- Mad Libs Array

**Expected outcome:**
-Array of true/false statements. Examples:

${cast.name[0]} starred in ${movies.title}
${title}'s cast included ${cast.name[0]}

### PR DESCRIPTION
**Pull request by garanico**
## Changes
1. Add false performer-related questions to the Mad Libs Array

## Purpose
The purpose was to add false performer-related questions with the same format as the true questions

## Approach
This is a new feature

## Learning
This is an addition to the existing code that follows the same format

### CODE REVIEW

**Review by garetshough14 — CHANGES_REQUESTED** [review]
Hey grace, when I was checking the branch I noticed that the branch wasn't fully updated with all current changes. Can you pull all recent changes and commit to see if this branch is compatible with the newest version of development.

**Comment by garanico** [comment]
@garetshough14 I just merged again from the develop branch, but I just realized that I also accidentally merged another bug ticket's branch into this branch.  I'll either have to figure out how to roll back those changes or I can wait until that ticket has been merged and I can pull from develop again.

**Comment by garetshough14** [comment]
Ahh I see, yeah I've done that before as well, I think the best thing to do is ask Juan what the best course of action would be and we can start from there! @garanico

**Comment by garanico** [comment]
@garetshough14 I was able to fix my branch and merge the latest from the develop branch.  This is good for you to review again.  Let me know if you need anything!

**Comment by luceroweb** [comment]
@garanico 
cc @garanico @Tesfa-Worku @srosenberg74 
Since there has been some confusion about an accidental merge in this branch, please:
1. Cancel this pull request
2. Create a new branch off of `develop`
3. Add the new questions in that branch
4. Create a new pull request

**Comment by garanico** [comment]
Closing this pull request.  This will be resolved in pull request #84

**Pull request closed without merging**
