### PR TITLE
Fix footer on mobile #59

### LINKED ISSUE #59: Fix footer on mobile
**Date Seen**
3/10/22 12pm

**Versions**
Android & iPhone
Expo Android, Expo iPhone
[develop](https://github.com/luceroweb/guess-the-movie/tree/develop)

**Bug Description**
On mobile, links on the footer are non existent but on web the links are showing as planned.

**Steps to Reproduce**
1. Open app
2. Notice footer on "Main" scene does not contain the footer links
3. Click to start game, footer is not present (as expected)
4. choose correct answer, footer is not present (as expected)
5. Choose incorrect answer, footer does not contain the footer links

**Actual Behavior**
Footer does not contain links on Android and iPhone in the Expo emulator on the Main and GameOver scenes.

**Expected Behavior**
The about and developer links are suppose to be shown in the footer on the Android and iPhone Expo emulators as they are on the web version.

**Troubleshooting/Testing Steps Attempted**
tried scrolling page, no result, footer is pushed down below the bottom of the screen

**Workaround**
none

### PR DESCRIPTION
**Pull request by Hiwot-Beshe**
Fix the footer {Credit and About} nav title make at the center on mobile.

### CODE REVIEW

**Review by garetshough14 — APPROVED** [review]
Everything seems to be working fine on my end good work you can go ahead and merge now!

**Comment by garetshough14** [comment]
Hiwot, everything seemed to be fine but there is one issue. Can you please make a new pull request and remove the border bottom. After that is completed you should be fully completed!

**Comment by luceroweb** [comment]
@Hiwot-Beshe @darlanebrown @garetshough14 @keshi2021 This ticket fully resolves the bug that was identified, however, I'm concerned about the complexity of the solution to display the line through color since it may be difficult to developers to understand when they inherit this code. I'll put a low-priority refactor ticket in the backlog to try to find a simpler solution to the problem in the future, and accept this pull request now, so we can get the solution to production qucikly.

**Comment by luceroweb** [comment]
@Hiwot-Beshe @darlanebrown @garetshough14 @keshi2021 This ticket fully resolves the bug that was identified, however, I'm concerned about the complexity of the solution to display the line through color since it may be difficult to developers to understand when they inherit this code. I'll put a low-priority refactor ticket in the backlog to try to find a simpler solution to the problem in the future, and accept this pull request now, so we can get the solution to production qucikly.

**Pull request merged**
