### PR TITLE
Ml2 settings modal 25

### LINKED ISSUE #25: Game Settings (modal)
[timebox: , complexity points: ]

As a user, I want to see a settings icon in the header at all times, so that when I click the icon (while not in active game mode), the settings modal will be displayed.

**User Expectations:**
- Display a settings (gear) icon on the top right of the header
- Click the settings icon to open the settings modal

**Developer Dependencies:**
- Add a settings (gear) icon to the top right of the header
- Create a blank modal with a heading of "Settings" and a close button/icon
- Display the settings modal, when the gear icon is clicked/tapped
- Close the settings modal when the close button/icon is clicked/tapped
- Disable & grey out the settings icon on the Question & CorrectAnswer scenes

### PR DESCRIPTION
**Pull request by luceroweb**
From Garet: Add gear icon to the header that when clicked/tapped, a opens a modal. Click/tap a back arrow icon to close the modal.

### CODE REVIEW

**Comment by luceroweb** [comment]
@garetshough14 @ProjectErostribe 
A few comments on this ticket:
- Don't forget to confirm that you have met all ticket requirements before submitting a pull request
- Don't forget to pull in and merge the latest from the `develop` branch when submitting an update to this ticket.
- Please remove unneeded Views and Styles including but not limited to `<View style={styles.centeredView}>` and `styles.buttonOpen`
- Consider moving the `SettingsModal.js` component to the `Components` folder
- Remove the `Alert.alert("Modal has been closed.");` from `onRequestClose` since it's not used or needed
- Change the close icon to an `X`
- Move the close icon to the top right of the modal
- Disable & grey out the settings icon on the `Question.js` and `CorrectAnswer.js` scenes (use Redux state to determine whether to disable and grey out the settings icon)

**Comment by garetshough14** [comment]
This Ticket is almost done, The only task I need to complete is some testing on android and IOS.

**Comment by SmiJa** [comment]
@garetshough14 disable( don't show ) the gear in the game mode.

**Review by garetshough14 — APPROVED** [review]
Everything seems to be working as planned!

**Pull request merged**
